"""empty message

Revision ID: 80a360e25cfe
Revises: 678363f2cee5
Create Date: 2021-07-26 01:37:49.121929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80a360e25cfe'
down_revision = '678363f2cee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_project_timestamp'), 'project', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_timestamp'), table_name='project')
    op.drop_column('project', 'timestamp')
    # ### end Alembic commands ###
